### ISSUE TITLE
Wrong credentials in file get-ap-xml-1.py

### ISSUE THREAD

**Issue by AntoineOrsoni** [CiscoDevNet/coding-skills-sample-code#13]
Credentials are wrong in the files in the following forlder: **coding-skills-sample-code/coding201-parsing-xml/**

Executing the script returns:
`urllib.error.HTTPError: HTTP Error 401: Error while Authenticating the User`

**Comment by kils17** [comment]
please modify the authenticator as below, but the URL is not available.. change the URL as below too, then you can get the response string, but it is not parsed by xml.dom.minidom because it's JSON file, so you can use this URL in the 'https://developer.cisco.com/learning/lab/coding-202-parsing-json/step/2' 

#req = Request('https://cmxlocationsandbox.cisco.com/api/contextaware/v1/maps/info/DevNetCampus/DevNetBuilding/DevNetZone')
req = Request('https://cmxlocationsandbox.cisco.com/api/config/v1/maps')
#req.add_header('Authorization', 'Basic bGVhcm5pbmc6bGVhcm5pbmc==')
req.add_header('Authorization', 'Basic bGVhcm5pbmc6bGVhcm5pbmc=')

**Comment by adewunmi-03** [comment]
python get-ap-json.py
Traceback (most recent call last):
  File "get-ap-json.py", line 1, in <module>
    from urllib.request import Request, urlopen
ImportError: No module named request

**Comment by lars96** [comment]
certificate has been expired..

**Comment by tebycardona-net** [comment]
Hi, Does anyone get a workaround for this lab?

Thanks !

**Comment by annegentle** [comment]
Hi, this has been re-written to work against an ACI Always-On DevNet Sandbox instead, so closing this Issue.
